### ISSUE TITLE
Not working with English option

### ISSUE THREAD

**Issue by shillshocked** [ShanaMaid/terminal-translate#8]
tl -t en bonjour gives:
`fs.js:133
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.writeFile (fs.js:1179:14)
    at Object.<anonymous> (/usr/lib/node_modules/terminal-translate/bin/translate.js:51:10)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
    at internal/main/run_main_module.js:21:11
`

**Comment by ShanaMaid** [comment]
please install terminal-translate@1.0.6, do this
```
tl -t en
tl bonjour
```
